[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://riaak.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

